#include <string.h>
#include "pico/stdlib.h"
#include "hardware/clocks.h"
#include "hardware/vreg.h"
#include "hardware/pwm.h"

#include "hw_config.h"
#include "display.h"
#include "input.h"

// Audio library
#define AUDIO_SAMPLE_RATE 32768
#include "minigb_apu.h"

// Forward-declare audio callbacks before Peanut-GB includes them
uint8_t audio_read(uint16_t addr);
void audio_write(uint16_t addr, uint8_t val);

// Peanut-GB — single-header Game Boy emulator
#include "peanut_gb.h"

// ROM compiled into flash (generated by tools/convert_rom.py)
#include "rom_data.h"

// Cart RAM (max 32 KB for MBC3/MBC5)
static uint8_t cart_ram[32768];

// Framebuffer: GB native resolution, native RGB565
static uint16_t framebuf[GB_LCD_WIDTH * GB_LCD_HEIGHT];

// Grayscale palette — native RGB565 (byte order handled by display driver)
static const uint16_t palette[4] = {
    0xFFFF,  // White (lightest)
    0xAD55,  // Light gray
    0x528A,  // Dark gray
    0x0000,  // Black (darkest)
};

// --- Audio ---

static struct minigb_apu_ctx apu;

// Double buffer for timer-driven audio output
#define AUDIO_BUF_LEN 600
static uint8_t audio_pwm_buf[2][AUDIO_BUF_LEN];
static volatile uint8_t audio_play_idx;
static volatile uint16_t audio_sample_pos;
static volatile uint16_t audio_sample_count;
static struct repeating_timer audio_timer;

uint8_t audio_read(uint16_t addr) {
    return minigb_apu_audio_read(&apu, addr);
}

void audio_write(uint16_t addr, uint8_t val) {
    minigb_apu_audio_write(&apu, addr, val);
}

static bool audio_timer_callback(struct repeating_timer *t) {
    (void)t;
    if (audio_sample_pos < audio_sample_count) {
        pwm_set_gpio_level(PIN_AUDIO, audio_pwm_buf[audio_play_idx][audio_sample_pos]);
        audio_sample_pos++;
    }
    return true;
}

static void audio_init(void) {
    gpio_init(PIN_AMP_EN);
    gpio_set_dir(PIN_AMP_EN, GPIO_OUT);
    gpio_put(PIN_AMP_EN, 1);

    gpio_set_function(PIN_AUDIO, GPIO_FUNC_PWM);
    uint pwm_slice = pwm_gpio_to_slice_num(PIN_AUDIO);
    pwm_set_wrap(pwm_slice, 255);
    pwm_set_clkdiv(pwm_slice, 1.0f);
    pwm_set_enabled(pwm_slice, true);

    minigb_apu_audio_init(&apu);

    audio_play_idx = 0;
    audio_sample_pos = 0;
    audio_sample_count = 0;

    // Timer at 32768 Hz = every ~30.5 µs
    // Negative value = exact interval regardless of callback duration
    add_repeating_timer_us(-30, audio_timer_callback, NULL, &audio_timer);
}

static void audio_play_frame(void) {
    // Generate raw stereo samples
    static audio_sample_t raw_buf[1200];
    minigb_apu_audio_callback(&apu, raw_buf);

    // Fill the inactive buffer (mix stereo→mono, convert s16→u8)
    uint8_t fill_idx = audio_play_idx ^ 1;
    uint16_t count = AUDIO_SAMPLES;
    if (count > AUDIO_BUF_LEN) count = AUDIO_BUF_LEN;

    for (uint16_t i = 0; i < count; i++) {
        int32_t left  = raw_buf[i * 2];
        int32_t right = raw_buf[i * 2 + 1];
        int32_t mono  = (left + right) / 2;
        uint8_t pwm_val = (uint8_t)((mono + 32768) >> 8);
        // 50% volume: bias toward center (128)
        audio_pwm_buf[fill_idx][i] = 128 + ((int)(pwm_val) - 128) / 2;
    }

    // Swap: ISR starts reading from the newly filled buffer
    audio_sample_count = count;
    audio_sample_pos = 0;
    audio_play_idx = fill_idx;
}

// --- Peanut-GB callbacks ---

uint8_t gb_rom_read(struct gb_s *gb, const uint_fast32_t addr) {
    (void)gb;
    return rom_data[addr];
}

uint8_t gb_cart_ram_read(struct gb_s *gb, const uint_fast32_t addr) {
    (void)gb;
    return cart_ram[addr];
}

void gb_cart_ram_write(struct gb_s *gb, const uint_fast32_t addr, const uint8_t val) {
    (void)gb;
    cart_ram[addr] = val;
}

void gb_error(struct gb_s *gb, const enum gb_error_e err, const uint16_t addr) {
    (void)gb;
    (void)err;
    (void)addr;
}

void lcd_draw_line(struct gb_s *gb, const uint8_t *pixels, const uint_fast8_t line) {
    (void)gb;
    uint16_t *dst = &framebuf[line * GB_LCD_WIDTH];
    for (int x = 0; x < GB_LCD_WIDTH; x++) {
        uint8_t shade = pixels[x] & 0x03;
        dst[x] = palette[shade];
    }
}

// --- Main ---

int main(void) {
    vreg_set_voltage(VREG_VOLTAGE_1_20);
    sleep_ms(10);
    set_sys_clock_khz(250000, true);

    stdio_init_all();
    display_init();
    input_init();
    audio_init();

    struct gb_s gb;
    enum gb_init_error_e err = gb_init(&gb,
        gb_rom_read, gb_cart_ram_read, gb_cart_ram_write,
        gb_error, NULL);

    if (err != GB_INIT_NO_ERROR) {
        display_fill(0xF800);
        while (1) tight_loop_contents();
    }

    gb_init_lcd(&gb, lcd_draw_line);

    // Main emulation loop
    while (1) {
        joypad_t jp = input_read();
        gb.direct.joypad = jp.byte;

        gb_run_frame(&gb);

        display_frame(framebuf);
        audio_play_frame();
    }
}
